'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource_PL
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VBlib.Resource_PL", GetType(Resource_PL).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PL.
        '''</summary>
        Friend Shared ReadOnly Property _lang() As String
            Get
                Return ResourceManager.GetString("_lang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cache wyczyszczony.
        '''</summary>
        Friend Shared ReadOnly Property msgCacheCleared() As String
            Get
                Return ResourceManager.GetString("msgCacheCleared", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usunąć wszystko z tego feed?.
        '''</summary>
        Friend Shared ReadOnly Property msgDelAllFromThisFeed() As String
            Get
                Return ResourceManager.GetString("msgDelAllFromThisFeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usunąć wszystko z tego feed?.
        '''</summary>
        Friend Shared ReadOnly Property msgDelAllFromThisFeed1() As String
            Get
                Return ResourceManager.GetString("msgDelAllFromThisFeed1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filtr (wyrażenie regularne), ważne 14 dni:.
        '''</summary>
        Friend Shared ReadOnly Property msgKillFile14days() As String
            Get
                Return ResourceManager.GetString("msgKillFile14days", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filtr (wyrażenie regularne), ważne 14 dni:.
        '''</summary>
        Friend Shared ReadOnly Property msgKillFile14days1() As String
            Get
                Return ResourceManager.GetString("msgKillFile14days1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Podaj fragment Tytułu do usuwania.
        '''</summary>
        Friend Shared ReadOnly Property msgSubjectToRemove() As String
            Get
                Return ResourceManager.GetString("msgSubjectToRemove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Podaj fragment Tytułu do usuwania.
        '''</summary>
        Friend Shared ReadOnly Property msgSubjectToRemove1() As String
            Get
                Return ResourceManager.GetString("msgSubjectToRemove1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zmieniono White/BlackList, zapisać je?.
        '''</summary>
        Friend Shared ReadOnly Property msgWhiteBlackChanged() As String
            Get
                Return ResourceManager.GetString("msgWhiteBlackChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tak.
        '''</summary>
        Friend Shared ReadOnly Property msgYes() As String
            Get
                Return ResourceManager.GetString("msgYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browser.
        '''</summary>
        Friend Shared ReadOnly Property resBrowser() As String
            Get
                Return ResourceManager.GetString("resBrowser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usuń.
        '''</summary>
        Friend Shared ReadOnly Property resDelete() As String
            Get
                Return ResourceManager.GetString("resDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jednak nie.
        '''</summary>
        Friend Shared ReadOnly Property resDlgCancel() As String
            Get
                Return ResourceManager.GetString("resDlgCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wykonaj.
        '''</summary>
        Friend Shared ReadOnly Property resDlgContinue() As String
            Get
                Return ResourceManager.GetString("resDlgContinue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie.
        '''</summary>
        Friend Shared ReadOnly Property resDlgNo() As String
            Get
                Return ResourceManager.GetString("resDlgNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tak.
        '''</summary>
        Friend Shared ReadOnly Property resDlgYes() As String
            Get
                Return ResourceManager.GetString("resDlgYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Błąd wczytywania danych XML.
        '''</summary>
        Friend Shared ReadOnly Property resErrorReadingXML() As String
            Get
                Return ResourceManager.GetString("resErrorReadingXML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Podaj Uri nowego feed.
        '''</summary>
        Friend Shared ReadOnly Property resNewFeed() As String
            Get
                Return ResourceManager.GetString("resNewFeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nowe elementy w feed.
        '''</summary>
        Friend Shared ReadOnly Property resNewItemsInFeed() As String
            Get
                Return ResourceManager.GetString("resNewItemsInFeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lista nowych.
        '''</summary>
        Friend Shared ReadOnly Property resNewItemsList() As String
            Get
                Return ResourceManager.GetString("resNewItemsList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pokaż.
        '''</summary>
        Friend Shared ReadOnly Property resOpen() As String
            Get
                Return ResourceManager.GetString("resOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nazwy feed.
        '''</summary>
        Friend Shared ReadOnly Property resRenameTitle() As String
            Get
                Return ResourceManager.GetString("resRenameTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bez toast.
        '''</summary>
        Friend Shared ReadOnly Property resToastType0() As String
            Get
                Return ResourceManager.GetString("resToastType0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Info że coś jest.
        '''</summary>
        Friend Shared ReadOnly Property resToastType1() As String
            Get
                Return ResourceManager.GetString("resToastType1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lista nowych.
        '''</summary>
        Friend Shared ReadOnly Property resToastType2() As String
            Get
                Return ResourceManager.GetString("resToastType2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oddzielne.
        '''</summary>
        Friend Shared ReadOnly Property resToastType3() As String
            Get
                Return ResourceManager.GetString("resToastType3", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
